#' Preview a colour palette as a strip plot
#'
#' Displays a horizontal strip of colour swatches. Useful for quickly
#' inspecting palettes generated by okpal functions.
#'
#' @param colours Character vector of hex colour strings.
#' @param labels Logical; show hex labels on swatches (default FALSE for
#'   palettes with > 20 colours, TRUE otherwise).
#' @param main Title for the plot (default NULL).
#' @return Invisible NULL. Called for its side effect of producing a plot.
#' @export
#' @examples
#' plot_palette(oklab_seq("#1B0A55", "#FDE725", n = 12))
#' plot_palette(oklch_qualitative(8))
plot_palette <- function(colours, labels = NULL, main = NULL) {
  .check_hex(colours, "colours")
  n <- length(colours)
  if (is.null(labels)) labels <- (n <= 20)

  oldpar <- graphics::par(mar = c(1, 1, if (!is.null(main)) 2 else 1, 1))
  on.exit(graphics::par(oldpar))

  graphics::image(
    x = seq_len(n), y = 1, z = matrix(seq_len(n), ncol = 1),
    col = colours, axes = FALSE, xlab = "", ylab = "", main = main
  )

  if (labels) {
    graphics::text(
      x = seq_len(n), y = 1, labels = colours,
      cex = max(0.4, min(0.8, 12 / n)),
      srt = 90, col = ifelse(
        farver::decode_colour(colours, to = "oklab")[, "l"] > 0.6,
        "black", "white"
      )
    )
  }

  invisible(NULL)
}
